##################################
#	        Settings file          #
##################################
#   Keys are given as keycode,   #
#   read the keycode.txt file    #
##################################
#                                #
# Note: Make sure you use spaces #
# for indentation, not tabs!     #
#                                #
##################################

# Settings related to the game window
window:
  fullscreen: false
  width: 768
  height: 512

game:

  # If set to true no software mouse will be rendered
  # Will be deprecated if I manage to change the
  # OS cursor!
  # Useful if your mouse lags
  use_hardware_mouse: false

  # May improve framerate when moving units
  # but will add a slight order delay when
  # doing big paths or similar
  threaded_pathfinding: true

  # Delay when giving orders to multiple
  # units. May reduce group jitter
  group_order_delay: 0.5

# Settings related to the controls
controls:

  select_multiple_keys:
     - 38   #LShift
	

  # Used for when a mine order is ambiguous
  # with a walk/attack order
  force_order_mine_keys:
     - 12   # M

  zoom_speed:
    slow: 0.4
    fast: 1.2

  increase_zoom_keys:
    - 17   # R

  decrease_zoom_keys:
    - 5    # F

  speed_keys:
    - 37   # LCTRL
    - 21   # V

  up_keys:
    - 22   # W
    - 73   # Up arrow

  right_keys:
    - 3    # D
    - 72   # Right arrow

  down_keys:
    - 18   # S
    - 74   # Down arrow

  left_keys:
    - 0    # A
    - 71   # Left Arrow

  # Allow scrolling to be done with the mouse?
  allow_mouse_scroll: false

  # Allow offscreen scrolling
  offscreen_scroll: true

  # Allow both keyboard and mouse scrolling at the same time?
  allow_double_scroll: false

  # Speeds of scrolling
  scroll_speed:
    slow: 180
    fast: 360

  # Triggers for mouse based scrolling
  triggers:
    left: 0.2
    right: 0.8
    top: 0.2
    down: 0.8
